import mainBg from "$/main_bg.webp";
import type { Metadata } from "next";
import { Great_Vibes, Poiret_One } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const primary = Poiret_One({
  weight: ["400"],
  variable: "--font-primary",
  subsets: ["latin"],
});

const secondary = Great_Vibes({
  weight: ["400"],
  variable: "--font-secondary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={"h-full w-full  scroll-smooth"}>
      <body
        className={`${primary.variable} ${secondary.variable} font-primary antialiased  flex flex-col justify-center items-center text-stone-800 relative h-full w-full`}
      >
        <Image src={mainBg} fill className="object-cover" priority alt="" />
        <div className="bg-amber-900/5 absolute inset-0"></div>

        <main className="text-3xl  h-full w-full items-center font-bold  overflow-x-hidden flex flex-col justify-between absolute gap-30 inset-0 overflow-auto px-4  pb-40">
          {children}
        </main>
      </body>
    </html>
  );
}
